### ISSUE TITLE
Most engines do not work

### ISSUE THREAD

**Issue by CNSabata** [sta0003/EngineHoist#10]
**Describe the bug**
Message shows a an error when selecting engines from all the categories other than ATG-VIDEO-1

**To Reproduce**

1. Click on a category other than ATG-VIDEO-1
1. Click "start simulator

**Expected behavior**
The simulator starts with the engine I selected (ex: 2JZ)

**Screenshots**
![image](https://user-images.githubusercontent.com/20067074/193287442-2e8f6a52-9ee4-4a76-b16d-0eb486134053.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/1RHs7G2R) by [Unito](https://www.unito.io)

**Comment by Peugeot205GTI** [comment]
i have the same issue

**Comment by sta0003** [comment]
Hi, I am aware of this issue have been getting many reports. Are you able to provide a copy of an engine file that works and doesn't.
Thanks

**Comment by PieMan28** [comment]
I am having the same issue. I believe that it works for engines in the first folder, but for me, the second folder works as well. I only have had this issue with 1.11 for the sim and 1.3 for the engine selector.

**Comment by CNSabata** [comment]
> Hi, I am aware of this issue have been getting many reports. Are you able to provide a copy of an engine file that works and doesn't. Thanks
> 
> (EDIT) I believe this issue is for anything that is not in the first folder.

Yes, you are perfectly right.
Sorry for not answering earlier, busy weekend.
Cheers

**Comment by Peugeot205GTI** [comment]
i think its because engine hoist always use the set_engine(engine()) function even if the engine has the main() function like the harley davidson shovelhead

**Comment by PieMan28** [comment]
Ok... so do we have a solution?

**Comment by Peugeot205GTI** [comment]
i will try to force the main() function just to see

**Comment by sta0003** [comment]
I'm still working on the next version sorry for the delay been busy school week.

**Comment by sta0003** [comment]
Fixed in new version 1.4.0
