### ISSUE TITLE
Transmission (and often) vehicle not loading

### ISSUE THREAD

**Issue by DamogaPro** [sta0003/EngineHoist#16]
**Describe the bug**

**To Reproduce**
1. Load an engine that has a custom transmission or a custom vehicle with Engine Hoist

**Expected behavior**
It loads the custom transmission and the vehicle

**Screenshots**
If I load the engine without the Engine Hoist, it loads the custom transmission and vehicle

![Engine Sim _ AngeTheGreat _ v0 1 11a 17_12_2022 15_00_16](https://user-images.githubusercontent.com/120792758/208245773-318d4042-f582-4ecb-a03b-734bcd014aaa.png)
But if I load it by the Engine Hoist it never loads the custom transmission and often dont load the custom vehicle
![Engine Sim _ AngeTheGreat _ v0 1 11a 17_12_2022 15_03_14](https://user-images.githubusercontent.com/120792758/208245774-b076a53b-efc1-4c17-962e-a8ed9dd33cad.png)

**Comment by sta0003** [comment]
Hi,
I will have to look into this are you able to supply the engine file that your are having issues with.

**Comment by DamogaPro** [comment]
[f1.zip](https://github.com/sta0003/EngineHoist/files/10252721/f1.zip)
but it ocurrs in every motor with custom transmission

**Comment by DamogaPro** [comment]
I have putted the photos in the wrong order.

**Comment by sta0003** [comment]
3+ Months Stale
